// Barrel re-exports for backward compatibility during migration
export { Header } from './layout/Header';
export { Footer } from './layout/Footer';
export { BackgroundPattern } from './layout/BackgroundPattern';
export { WhatsAppButton } from './shared/WhatsAppButton';
export { LanguageSwitcher } from './shared/LanguageSwitcher';
export { NavLink } from './shared/NavLink';
export { default as ProtectedRoute } from './shared/ProtectedRoute';
export { HeroSection } from './home/HeroSection';
export { FeaturesSection } from './home/FeaturesSection';
export { CorePrinciplesSection } from './home/CorePrinciplesSection';
export { HowItWorks } from './home/HowItWorks';
export { HowItWorksTimeline } from './home/HowItWorksTimeline';
export { Testimonials } from './home/Testimonials';
export { WhyOnlinePooja } from './home/WhyOnlinePooja';
export { FAQ } from './home/FAQ';
export { TempleGateIntro } from './home/TempleGateIntro';
export { UpcomingRituals } from './home/UpcomingRituals';
export { ServiceCard } from './services/ServiceCard';
export type { Service } from './services/ServiceCard';
export { ServiceFilters } from './services/ServiceFilters';
export type { FilterState } from './services/ServiceFilters';
export { PoojaListingCard } from './services/PoojaListingCard';
export { PoojaFilters } from './services/PoojaFilters';
export { PaymentStep } from './booking/PaymentStep';
export { EventCard } from './booking/EventCard';
export { PanchangCalendar } from './panchang/PanchangCalendar';
export { PanchangSection } from './panchang/PanchangSection';
export { MuhuratFinder } from './panchang/MuhuratFinder';
export { NorthIndianChart } from './panchang/NorthIndianChart';
export { FestivalList } from './panchang/FestivalList';
export { TempleCard } from './temple/TempleCard';
export { PunditCard } from './pundit/PunditCard';
